export const countryDetails = {
    USD: { name: 'United States', flag: '🇺🇸' },
    INR: { name: 'India', flag: '🇮🇳' },
    EUR: { name: 'Eurozone', flag: '🇪🇺' },
    GBP: { name: 'United Kingdom', flag: '🇬🇧' },
    AUD: { name: 'Australia', flag: '🇦🇺' },
    CAD: { name: 'Canada', flag: '🇨🇦' },
    CHF: { name: 'Switzerland', flag: '🇨🇭' },
    CNY: { name: 'China', flag: '🇨🇳' },
    JPY: { name: 'Japan', flag: '🇯🇵' },
    NZD: { name: 'New Zealand', flag: '🇳🇿' },
    SEK: { name: 'Sweden', flag: '🇸🇪' },
    NOK: { name: 'Norway', flag: '🇳🇴' },
    DKK: { name: 'Denmark', flag: '🇩🇰' },
    SGD: { name: 'Singapore', flag: '🇸🇬' },
    HKD: { name: 'Hong Kong', flag: '🇭🇰' },
    MXN: { name: 'Mexico', flag: '🇲🇽' },
    ZAR: { name: 'South Africa', flag: '🇿🇦' },
    BRL: { name: 'Brazil', flag: '🇧🇷' },
    RUB: { name: 'Russia', flag: '🇷🇺' },
    TRY: { name: 'Turkey', flag: '🇹🇷' },
    KRW: { name: 'South Korea', flag: '🇰🇷' },
    MYR: { name: 'Malaysia', flag: '🇲🇾' },
    IDR: { name: 'Indonesia', flag: '🇮🇩' },
    THB: { name: 'Thailand', flag: '🇹🇭' },
    VND: { name: 'Vietnam', flag: '🇻🇳' },
    PHP: { name: 'Philippines', flag: '🇵🇭' },
    SAR: { name: 'Saudi Arabia', flag: '🇸🇦' },
    AED: { name: 'United Arab Emirates', flag: '🇦🇪' },
    QAR: { name: 'Qatar', flag: '🇶🇦' },
    KWD: { name: 'Kuwait', flag: '🇰🇼' },
    BHD: { name: 'Bahrain', flag: '🇧🇭' },
    OMR: { name: 'Oman', flag: '🇴🇲' },
    PLN: { name: 'Poland', flag: '🇵🇱' },
    CZK: { name: 'Czech Republic', flag: '🇨🇿' },
    HUF: { name: 'Hungary', flag: '🇭🇺' },
    RON: { name: 'Romania', flag: '🇷🇴' },
    ISK: { name: 'Iceland', flag: '🇮🇸' },
    ARS: { name: 'Argentina', flag: '🇦🇷' },
    CLP: { name: 'Chile', flag: '🇨🇱' },
    COP: { name: 'Colombia', flag: '🇨🇴' },
    PEN: { name: 'Peru', flag: '🇵🇪' },
    EGP: { name: 'Egypt', flag: '🇪🇬' },
    MAD: { name: 'Morocco', flag: '🇲🇦' },
    NGN: { name: 'Nigeria', flag: '🇳🇬' },
    GHS: { name: 'Ghana', flag: '🇬🇭' },
    KES: { name: 'Kenya', flag: '🇰🇪' },
    UGX: { name: 'Uganda', flag: '🇺🇬' },
    TZS: { name: 'Tanzania', flag: '🇹🇿' },
    XOF: { name: 'West African CFA Franc', flag: '🇨🇫' },
    XAF: { name: 'Central African CFA Franc', flag: '🇨🇲' },
    ZMW: { name: 'Zambia', flag: '🇿🇲' },
    BWP: { name: 'Botswana', flag: '🇧🇼' },
    RWF: { name: 'Rwanda', flag: '🇷🇼' },
    BDT: { name: 'Bangladesh', flag: '🇧🇩' },
    LKR: { name: 'Sri Lanka', flag: '🇱🇰' },
    NPR: { name: 'Nepal', flag: '🇳🇵' },
    PKR: { name: 'Pakistan', flag: '🇵🇰' },
    JOD: { name: 'Jordan', flag: '🇯🇴' },
    ILS: { name: 'Israel', flag: '🇮🇱' },
    DOP: { name: 'Dominican Republic', flag: '🇩🇴' },
    CRC: { name: 'Costa Rica', flag: '🇨🇷' },
    UYU: { name: 'Uruguay', flag: '🇺🇾' },
    PYG: { name: 'Paraguay', flag: '🇵🇾' },
    BOB: { name: 'Bolivia', flag: '🇧🇴' },
    VES: { name: 'Venezuela', flag: '🇻🇪' },
    BYN: { name: 'Belarus', flag: '🇧🇾' },
    KZT: { name: 'Kazakhstan', flag: '🇰🇿' },
    UAH: { name: 'Ukraine', flag: '🇺🇦' },
    GEL: { name: 'Georgia', flag: '🇬🇪' },
    AMD: { name: 'Armenia', flag: '🇦🇲' },
    AZN: { name: 'Azerbaijan', flag: '🇦🇿' },
    TMT: { name: 'Turkmenistan', flag: '🇹🇲' },
    KGS: { name: 'Kyrgyzstan', flag: '🇰🇬' },
    TJS: { name: 'Tajikistan', flag: '🇹🇯' },
    MNT: { name: 'Mongolia', flag: '🇲🇳' },
    IRR: { name: 'Iran', flag: '🇮🇷' },
    IQD: { name: 'Iraq', flag: '🇮🇶' },
    YER: { name: 'Yemen', flag: '🇾🇪' },
    SYP: { name: 'Syria', flag: '🇸🇾' },
    LBP: { name: 'Lebanon', flag: '🇱🇧' }, 
    SVC: { name: 'El Salvador', flag: '🇸🇻' },
    AFC: { name: 'Afghanistan', flag: '🇦🇫' },
    HRK: { name: 'Croatia', flag: '🇭🇷' },
    LAK: { name: 'Laos', flag: '🇱🇦' },
    BIF: { name: 'Burundi', flag: '🇧🇮' },
    STN: { name: 'São Tomé and Príncipe', flag: '🇸🇹' },
    CDF: { name: 'Democratic Republic of the Congo', flag: '🇨🇩' },
    LSL: { name: 'Lesotho', flag: '🇱🇸' },
    MWK: { name: 'Malawi', flag: '🇲🇼' },
    SOS: { name: 'Somalia', flag: '🇸🇴' },
    SCR: { name: 'Seychelles', flag: '🇸🇨' },
    VEF: { name: 'Venezuela', flag: '🇻🇪' },
    SHP: { name: 'Saint Helena', flag: '🇸🇭' },
    BBD: { name: 'Barbados', flag: '🇧🇧' },
    TOP: { name: 'Tonga', flag: '🇹🇴' },
    CUC: { name: 'Cuba', flag: '🇨🇺' },
    FKP: { name: 'Falkland Islands', flag: '🇫🇰' },
    GNF: { name: 'Guinea', flag: '🇬🇳' },
    AWG: { name: 'Aruba', flag: '🇦🇼' },
    FJD: { name: 'Fiji', flag: '🇫🇯' },
    XCD: { name: 'East Caribbean', flag: '🇦🇮' },
    MUR: { name: 'Mauritius', flag: '🇲🇺' },
    KHR: { name: 'Cambodia', flag: '🇰🇭' },
    TND: { name: 'Tunisia', flag: '🇹🇳' },
    MMK: { name: 'Myanmar', flag: '🇲🇲' },
    BAM: { name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
    GYD: { name: 'Guyana', flag: '🇬🇾' },
    ALL: { name: 'Albania', flag: '🇦🇱' },
    NIO: { name: 'Nicaragua', flag: '🇳🇮' },
    KMF: { name: 'Comoros', flag: '🇰🇲' },
    
    AFN: { name: 'Afghanistan', flag: '🇦🇫' },
    MOP: { name: 'Macau', flag: '🇲🇴' },
    JEP: { name: 'Jersey', flag: '🇯🇪' },
    NSD: { name: 'Niue', flag: '🇳🇺' },
    AOA: { name: 'Angola', flag: '🇦🇴' },
    SLL: { name: 'Sierra Leone', flag: '🇸🇱' },
    PAB: { name: 'Panama', flag: '🇵🇦' },
    XPF: { name: 'French Polynesia', flag: '🇵🇫' },
    TWD: { name: 'Taiwan', flag: '🇹🇼' },
    MRU: { name: 'Mauritania', flag: '🇲🇷' },
    HTG: { name: 'Haiti', flag: '🇭🇹' },
    ZWL: { name: 'Zimbabwe', flag: '🇿🇼' },
    BTN: { name: 'Bhutan', flag: '🇧🇹' },
    CVE: { name: 'Cape Verde', flag: '🇨🇻' },
    SZL: { name: 'Eswatini', flag: '🇸🇿' },
    GGP: { name: 'Guernsey', flag: '🇬🇬' },
    CUP: { name: 'Cuba', flag: '🇨🇺' },
    RSD: { name: 'Serbia', flag: '🇷🇸' },
    HNL: { name: 'Honduras', flag: '🇭🇳' },
    KYD: { name: 'Cayman Islands', flag: '🇰🇾' },
    GTQ: { name: 'Guatemala', flag: '🇬🇹' },
    LRD: { name: 'Liberia', flag: '🇱🇷' },
    GIP: { name: 'Gibraltar', flag: '🇬🇮' },
    SLE: { name: 'Sierra Leone', flag: '🇸🇱' },
    ETB: { name: 'Ethiopia', flag: '🇪🇹' },
    SBD: { name: 'Solomon Islands', flag: '🇸🇧' },
    BGN: { name: 'Bulgaria', flag: '🇧🇬' },
    WST: { name: 'Samoa', flag: '🇼🇸' },
    MGA: { name: 'Madagascar', flag: '🇲🇬' },
    BZD: { name: 'Belize', flag: '🇧🇿' },
    IMP: { name: 'Isle of Man', flag: '🇮🇲' },
    LYD: { name: 'Libya', flag: '🇱🇾' },
    BND: { name: 'Brunei', flag: '🇧🇳' },
    JMD: { name: 'Jamaica', flag: '🇯🇲' },
    KPW: { name: 'North Korea', flag: '🇰🇵' },
    ERN: { name: 'Eritrea', flag: '🇪🇷' },
    ANG: { name: 'Netherlands Antillean guilder', flag: '🇨🇼' },
    BSD: { name: 'Bahamas', flag: '🇧🇸' },
    DZD: { name: 'Algeria', flag: '🇩🇿' },
    UZS: { name: 'Uzbekistan', flag: '🇺🇿' },
    BMD: { name: 'Bermuda', flag: '🇧🇲' },
    SDG: { name: 'Sudan', flag: '🇸🇩' },
    SRD: { name: 'Suriname', flag: '🇸🇷' },
    MDL: { name: 'Moldova', flag: '🇲🇩' },
    GMD: { name: 'Gambia', flag: '🇬🇲' },
    TTD: { name: 'Trinidad and Tobago', flag: '🇹🇹' },
    MVR: { name: 'Maldives', flag: '🇲🇻' },
    PGK: { name: 'Papua New Guinea', flag: '🇵🇬' },
    MKD: { name: 'North Macedonia', flag: '🇲🇰' },
    VUV: { name: 'Vanuatu', flag: '🇻🇺' },
    DJF: { name: 'Djibouti', flag: '🇩🇯' },
    MZN: { name: 'Mozambique', flag: '🇲🇿' },
  };
  